### PR TITLE
Using .env instead of server-locations.json for best practices

### PR DESCRIPTION
**Pull request by realrusssobti**
Best practices state that this is the correct course of action.

### CODE REVIEW

**Comment by aelamanc** [comment]
LGTM. Good thinking of using .env instead

**Comment by vboo123** [comment]
LGTM. ^^

**Comment by Joelsp19** [comment]
Yeah looks good - good catch!

**Comment by Arctic1ce** [comment]
Great idea to include the server locations in the .env file!

**Pull request merged**
