### PR TITLE
Design next UI 2

### PR DESCRIPTION
**Pull request by Joelsp19**
Revamped frontend to include next-UI. 
- Reformatted Sidebar with Sidebar component(collapsible)
- Added Table component
- Tooltips for the collapsible sidebar
- Takes care of overflow problems
- Styled navbar
- Implemented Dark Mode Switch
- Styled Login + Signup pages
Had to remove styling on Table component to fix "refreshing" error ... can fix if time permits

### CODE REVIEW

**Comment by vboo123** [comment]
Thanks for doing this, UI looks way better now haha

**Comment by aelamanc** [comment]
UI Looking really good. Good job with the refactoring

**Comment by realrusssobti** [comment]
UI looking slick, love the added pops of color. No changes on my end.

**Comment by Arctic1ce** [comment]
UI looks great, I'm going to go ahead and merge into master.

**Pull request merged**
